### ISSUE TITLE
部分文章官方有更新翻译，需要跟进么？

### ISSUE THREAD

**Issue by ysy950803** [Android-Jetpack-Chinese-Translation/android-jetpack-chinese-translation#7]
[“Hello, Jetpack”：开发您的第一个 Jetpack 应用](https://github.com/Android-Jetpack-Chinese-Translation/android-jetpack-chinese-translation/blob/master/ANDROID_JETPACK/B_Get_started/1_Build_your_first_Android_Jetpack_app.md) （[官翻](https://developer.android.google.cn/jetpack/docs/getting-started)）
[应用架构指南](https://github.com/Android-Jetpack-Chinese-Translation/android-jetpack-chinese-translation/blob/master/ANDROID_JETPACK/B_Get_started/2_Guide_to_app_architecture.md) （[官翻](https://developer.android.google.cn/jetpack/docs/guide)）
比如这两个，谷歌有中文翻译了，还有，第一个里面的图挂了。

**Comment by naco-siren** [comment]
哎最近几周感觉没时间管，就先扔那儿吧

**Comment by ysy950803** [comment]
@naco-siren OK有空我也可以看看。
